# Generated by Django 4.2.4 on 2023-08-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="نام برند")),
            ],
            options={
                "verbose_name": "برند\u200cها",
                "verbose_name_plural": "برند",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="رنگ")),
            ],
            options={
                "verbose_name": "رنگ",
                "verbose_name_plural": "رنگ\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="کشور")),
            ],
            options={
                "verbose_name": "کشور\u200cها",
                "verbose_name_plural": "کشور",
            },
        ),
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="ملیت")),
            ],
            options={
                "verbose_name": "ملیت\u200cها",
                "verbose_name_plural": "ملیت",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=50, unique=True, verbose_name="مدل"),
                ),
                ("price", models.PositiveIntegerField(verbose_name="قیمت")),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="سایز صفحه نمایش"
                    ),
                ),
                (
                    "inventory",
                    models.BooleanField(default=False, verbose_name="وضعیت موجودی"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phone.brand",
                        verbose_name="برند",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phone.color",
                        verbose_name="رنگ",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phone.country",
                        verbose_name="کشور",
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phone.nationality",
                        verbose_name="ملیت",
                    ),
                ),
            ],
            options={
                "verbose_name": "گوشی\u200cها",
                "verbose_name_plural": "گوشی",
            },
        ),
    ]
